

/**
 * The values which can be pulled from the controller.
 *
 */
public enum FieldTypes {
WORKINGTEAM, SPEED, AVGWEIGHT, ORGANIC,
SLAUGTHERAMOUNTNIGHT, SLAUGTHERAMOUNTDAY,
STOPNIGHT, STOPDAY,
DAYEXPECTED,
TOTALSLAUGTHERAMOUNT, EXPECTEDFINISH,
PRODUCTIONSTOPS, DAILYMESSAGES, EXPECTEDPERHOUR, CURRENTSLAUGHTERAMOUNT

}
